server.http.allowed-origin=*

spring.jpa.properties.hibernate.default_schema=public
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/login_test

spring.datasource.username=postgres
spring.datasource.password=admin

app.secret-key=8AA30BCF43AE9AD650E9B4FDBF57511E7263BCF11654A740CE0AFA2F7C678734
app.expiration-time=600000